dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker
  
addons:
apt:
  packages:
    - docker-ce
  
sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - df -h
  - ls -lhtr
#   - sudo apt-get -qq update
#   - sudo apt-get install -y ant-optional
#   - sudo pip install sphinx
#   - git clone https://github.com/bio-boris/mini_kb.git
#   - cd mini_kb; time docker-compose -f execution-engine.yml pull;
#   - cd mini_kb; time docker-compose -f execution-engine.yml up -d
  - df -h
  - docker ps
  - sudo sh -c "echo '127.0.0.1 nginx' >> /etc/hosts"
  - cat /etc/hosts
  - sudo mkdir /mnt/condor; sudo chmod 777 /mnt/condor;

  
env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "GEbQy4zR5hhHDzjoThGyCHZVmpEWKduwR/sZ1sR8csOYrfYqQTHinhAMY+KAdUhjJfWGwR9l2v2xkhyokzdADhKOqZJo7jkkioPEtENdocTWMYq7Qedg6kUCzcAutURIBCcoJtW4vrpGZ+1YR4vB8BhA11KA62QUbsQY3ds/LTg="
    - secure: "NbHt1OUyrTXmN+tYAFcGH3mxlxraDKJ6WQNTJTG+u+wTOzh2MU1bf59l+oanvqlydpd7ZzG7c2cUpje5hvBMEV9s9jwdWqTlGXHWpcU3a1wZdNOkkAPK0Cb3opabRLwIqjovaoAAouSJCq/jUADzhusjrZcn5JVA7sSpYyJT3uE="
script:
  - whoami
  - cp dev_tools/test.cfg.example test.cfg
  - cp dev_tools/deploy_local_minikb.cfg deploy.cfg
  - ./gradlew test --tests TestAlpineDeleteRunner --info
  - ./gradlew test --tests DockerTest
  - ./gradlew test --tests DExecEngineMongoDbTest
#   - make build-docker-image
after_success:
  - IMAGE_NAME=kbase/kb_njs_wrapper ./build/push2dockerhub.sh
